# tasks file for supervisor
---
- name: configure | stat directories
  stat:
    path: "{{ item }}/"
  register: stat_directories
  with_items:
    - "{{ supervisor_default_file | dirname }}"
    - "{{ supervisor_configuration_file | dirname }}"
    - "{{ supervisor_unix_http_server_file | dirname }}"
    - "{{ supervisor_supervisord_logfile | dirname }}"
    - "{{ supervisor_supervisord_pidfile | dirname }}"
    - "{{ supervisor_supervisord_childlogdir }}"
    - "{{ supervisor_include | dirname }}"
  tags:
    - supervisor-configure-directories
    - supervisor-configure-directories-stat

- name: configure | create directories
  file:
    path: "{{ item.item }}"
    state: directory
    owner: "{{ supervisor_system_user }}"
    group: "{{ supervisor_system_group }}"
    mode: 0755
  with_items: "{{ stat_directories.results }}"
  when: item.stat.exists == false
  tags:
    - supervisor-configure-directories
    - supervisor-configure-directories-create

- name: configure | update configuration file - /etc/default/supervisor
  template:
    src: "{{ supervisor_default_file.lstrip('/') }}.j2"
    dest: "{{ supervisor_default_file }}"
    owner: "{{ supervisor_system_user }}"
    group: "{{ supervisor_system_group }}"
    mode: 0644
  notify: restart supervisor
  tags:
    - supervisor-configure-configuration
    - supervisor-configure-configuration-default-supervisor

- name: configure | update configuration file - /etc/supervisor/supervisord.conf
  template:
    src: "{{ supervisor_configuration_file.lstrip('/') }}.j2"
    dest: "{{ supervisor_configuration_file }}"
    owner: "{{ supervisor_system_user }}"
    group: "{{ supervisor_system_group }}"
    mode: 0640
  notify: restart supervisor
  tags:
    - supervisor-configure-configuration
    - supervisor-configure-configuration-supervisord-conf
