# tasks file
---
- name: groups | update group configuration files (present)
  ansible.builtin.template:
    src: etc/supervisor/conf.d/group.conf.j2
    dest: "/etc/supervisor/conf.d/{{ item.key }}.conf"
    owner: "{{ supervisor_system_user }}"
    group: "{{ supervisor_system_group }}"
    mode: 0640
  with_dict: "{{ supervisor_groups_present }}"
  notify: restart supervisor
  tags:
    - supervisor-groups-present

- name: groups | update group configuration files (absent)
  ansible.builtin.file:
    path: "/etc/supervisor/conf.d/{{ item.key }}.conf"
    state: absent
  with_dict: "{{ supervisor_groups_absent }}"
  notify: restart supervisor
  tags:
    - supervisor-groups-absent
