# tasks file
---
- name: configure | systemd | update script
  ansible.builtin.template:
    src: "{{ supervisor_etc_systemd_file.lstrip('/') }}.j2"
    dest: "{{ supervisor_etc_systemd_file }}"
    owner: "{{ supervisor_system_user }}"
    group: "{{ supervisor_system_group }}"
    mode: 0644
  register: _update_systemd_script
  notify: restart supervisor
  tags:
    - supervisor-service-systemd-update

- name: service | systemd | reload
  ansible.builtin.systemd:
    daemon_reload: true
  when: _update_systemd_script is changed
  tags:
    - supervisor-service-systemd-reload
