# tasks file
---
- name: configure | initd | update script
  ansible.builtin.template:
    src: "{{ supervisor_etc_init_d_file.lstrip('/') }}.j2"
    dest: "{{ supervisor_etc_init_d_file }}"
    owner: "{{ supervisor_system_user }}"
    group: "{{ supervisor_system_group }}"
    mode: 0755
  notify: restart supervisor
  tags:
    - supervisor-service-upstart-update
