# handlers file for supervisor
---
- name: restart supervisor
  service:
    name: supervisor
    state: stopped
  service:
    name: supervisor
    state: started
  when: supervisor_state == 'started'
