# handlers file for supervisor
---
- name: restart supervisor
  # service module doesnt work sell with supervisor init script on ubuntu
  #service:
  #  name: supervisor
  #  state: restarted
  # using command line instead
  become: yes
  shell: "service supervisor restart"
  when: supervisor_state == 'started'

- name: update supervisor
  become: yes
  shell: "supervisorctl reread && supervisorctl update"
  # supervisorctl ansible module is buggy. using shell command instead.
